name: PR
on:
  pull_request:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.31.0, stable]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: dtolnay/rust-toolchain@439cf607258077187679211f12aa6f19af4a0af7 # master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo build
      - run: ./ci/test_full.sh

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@9e05a8b19349ee47e89b44a2ba5fb0a932eff356 # 1.62.0
        with:
          components: rustfmt
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: cargo fmt --all --check
